DemoCave1F_Text_GalarianYamask_Sign::
	.string "The end of this small corridor can make\n"
	.string "Galarian Yamask evolve from a script.\p"
	.string "First, add {FONT_CONSTANT}EVO_SCRIPT_TRIGGER, 0{FONT_REGULAR}\n"
	.string "to the evolution table.\p"
	.string "Then, call for {FONT_SCRIPT}tryspecialevo, {FONT_CONSTANT}0{FONT_REGULAR} in\n"
	.string "any script (NPC, trigger, etc.).\p"
	.string "To have more than 1 script evolution,\n"
	.string "change the {FONT_CONSTANT}0{FONT_REGULAR}s for a different number\l"
	.string "when adding to the evolution table.\p"
	.string "You can replicate Kubfu's evo in SwSh,\n"
	.string "by interacting with different scrolls.\p"
	.string "Or even make a story sequence that\n"
	.string "automatically triggers an evolution!\p"
	.string "Pressing B and evolving multiple mon\n"
	.string "can be disabled via optional parameters.$"

DemoCave1F_Text_GalarianYamask_StillYamask::
	.string "If your Galarian Yamask didn't evolve,\n"
	.string "it may haven't gotten 49 damage,\l"
	.string "or maybe you pressed B to cancel.$"

DemoCave1F_Text_Archie::
	.string "I hate these wall patterns so much.\n"
	.string "They look like bricks.$"
