DemoDeoxysEvent_Text_DeoxysRockSign:
	.string "The Deoxys Triangle has special\n"
	.string "handling defined in {FONT_NARROW}{COLOR BLUE}{SHADOW LIGHT_BLUE}field_specials.c\p"
	.string "{FONT_NORMAL}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "Search for {FONT_NARROW}{COLOR RED}{SHADOW LIGHT_RED}DoDeoxysRockInteraction"
	.string "{FONT_NORMAL}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}\n"
	.string "and {FONT_NARROW}{COLOR RED}{SHADOW LIGHT_RED}SetDeoxysRockPalette"
	.string "{FONT_NORMAL}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}.$"
