DemoTown_Text_LookingForTrade:
	.string "I'm an In-Game trade.\p"
	.string "I'll give you a {STR_VAR_2} in\n"
	.string "exchange for a {STR_VAR_1}.$"

DemoTown_Text_ThankYouForTheTrade:
	.string "Thank you for the {STR_VAR_1},\n"
	.string "Please take care of my {STR_VAR_2}.$"

DemoTown_Text_NotRequestedMon:
	.string "That's not a {STR_VAR_1},\n"
	.string "I can't give you my {STR_VAR_2} for it.$"

DemoTown_Text_DoYouWantARalts:
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Do you want a Ralts to test\n"
	.string "this feature?.$"

DemoTown_Text_CancelledTrade:
	.string "I see.\n"
	.string "We can do this another time.$"

DemoTown_Text_ReallyWantedToGetBagon:
	.string "Thank you for the trade!$" @ Does not buffer trade data

DemoTown_EventScript_Text_CantSeeMirageIslandToday:
	.string "I can't see MIRAGE ISLAND today…$"

DemoTown_EventScript_Text_CanSeeMirageIslandToday:
	.string "Oh! Oh my!\n"
	.string "I can see MIRAGE ISLAND today!$"
