DemoTown_Text_LookingForTrade:
	.string "I'm an In-Game trade.\p"
	.string "I'll give you a {STR_VAR_2} in\n"
	.string "exchange for a {STR_VAR_1}.$"

DemoTown_Text_ThankYouForTheTrade:
	.string "Thank you for the {STR_VAR_1},\n"
	.string "Please take care of my {STR_VAR_2}…$"

DemoTown_Text_NotRequestedMon:
	.string "That's not a {STR_VAR_1},\n"
	.string "I can't give you my {STR_VAR_2} for it.$"

DemoTown_Text_DoYouWantARalts:
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Do you want a Ralts to test\n"
	.string "this feature?$"

DemoTown_Text_CancelledTrade:
	.string "I see.\n"
	.string "We can do this another time.$"

DemoTown_EventScript_Text_CantSeeMirageIslandToday:
	.string "I can't see MIRAGE ISLAND today…$"

DemoTown_EventScript_Text_CanSeeMirageIslandToday:
	.string "Oh! Oh my!\n"
	.string "I can see MIRAGE ISLAND today!$"

DemoTown_Text_SeeHowMuchPokemonLikesYou:
	.string "Let's check your Pokémon's friendship…$"

DemoTown_Text_DetestsYou:
	.string "Frienship at 0.\p"
	.string "This is a little hard for me to say…\p"
	.string "Your POKéMON simply detests you.\n"
	.string "Doesn't that make you uncomfortable?$"

DemoTown_Text_VeryWary:
	.string "Frienship between 1 and 49.\p"
	.string "It's very wary.\n"
	.string "It has scary viciousness in its eyes.\l"
	.string "It doesn't like you much at all.$"

DemoTown_Text_NotUsedToYou:
	.string "Frienship between 50 and 99.\p"
	.string "It's not very used to you yet.\n"
	.string "It neither loves nor hates you.$"

DemoTown_Text_GettingUsedToYou:
	.string "Frienship between 100 and 149.\p"
	.string "It's getting used to you.\n"
	.string "It seems to believe in you.$"

DemoTown_Text_LikesYouQuiteALot:
	.string "Frienship between 150 and 199.\p"
	.string "It likes you quite a lot.\n"
	.string "It seems to want to be babied a little.$"

DemoTown_Text_VeryHappy:
	.string "Frienship between 200 and 254.\p"
	.string "It seems to be very happy.\n"
	.string "It obviously likes you a whole lot.$"

DemoTown_Text_AdoresYou:
	.string "Frienship at 255.\p"
	.string "It adores you.\n"
	.string "It can't possibly love you any more.\l"
	.string "I even feel happy seeing it.$"
