#ifndef GUARD_CONFIG_FRLG_BAG_OVERRIDE_H
#define GUARD_CONFIG_FRLG_BAG_OVERRIDE_H

#ifdef OVR_FRLG_I_USE_FRLG_BAG
#undef FRLG_I_USE_FRLG_BAG
#define FRLG_I_USE_FRLG_BAG                 OVR_FRLG_I_USE_FRLG_BAG
#endif

#endif // GUARD_CONFIG_FRLG_BAG_OVERRIDE_H
