#ifndef GUARD_CONFIG_SAVE_OVERRIDE_H
#define GUARD_CONFIG_SAVE_OVERRIDE_H

#ifdef OVR_RKSE_FREE_SAVE
#undef FREE_TRAINER_HILL
#define FREE_TRAINER_HILL                   FALSE
#undef FREE_TRAINER_TOWER
#define FREE_TRAINER_TOWER                  FALSE
#undef FREE_MYSTERY_EVENT_BUFFERS
#define FREE_MYSTERY_EVENT_BUFFERS          FALSE
#undef FREE_MATCH_CALL
#define FREE_MATCH_CALL                     FALSE
#undef FREE_UNION_ROOM_CHAT
#define FREE_UNION_ROOM_CHAT                FALSE
#undef FREE_ENIGMA_BERRY
#define FREE_ENIGMA_BERRY                   FALSE
#undef FREE_LINK_BATTLE_RECORDS
#define FREE_LINK_BATTLE_RECORDS            FALSE
#undef FREE_MYSTERY_GIFT
#define FREE_MYSTERY_GIFT                   FALSE
#undef FREE_SECRET_BASES
#define FREE_SECRET_BASES                   FALSE

#undef FREE_BATTLE_TOWER_E_READER
#define FREE_BATTLE_TOWER_E_READER          FALSE
#undef FREE_POKEMON_JUMP
#define FREE_POKEMON_JUMP                   FALSE
#undef FREE_RECORD_MIXING_HALL_RECORDS
#define FREE_RECORD_MIXING_HALL_RECORDS     FALSE
#undef FREE_FRONTIER_APPRENTICES
#define FREE_FRONTIER_APPRENTICES           FALSE
#endif

#endif // GUARD_CONFIG_SAVE_OVERRIDE_H
