#ifndef GUARD_CONFIG_TEST_OVERRIDE_H
#define GUARD_CONFIG_TEST_OVERRIDE_H

#ifdef OVR_T_SHOULD_RUN_MOVE_ANIM
#undef T_SHOULD_RUN_MOVE_ANIM
#define T_SHOULD_RUN_MOVE_ANIM              OVR_T_SHOULD_RUN_MOVE_ANIM
#endif

#endif // GUARD_CONFIG_TEST_OVERRIDE_H
