DemoRoute_Text_ChoosingRowlet::
	.string "Do you want to go with\n"
	.string "the Grass Pokémon Rowlet?$"

DemoRoute_Text_ChoosingOshawott::
	.string "Do you want to go with\n"
	.string "the Water Pokémon Oshawott?$"

DemoRoute_Text_ChoosingCyndaquil::
	.string "Do you want to go with\n"
	.string "the Fire Pokémon Cyndaquil?$"

DemoRoute_Text_ReceivedMon::
	.string "{PLAYER} received the {STR_VAR_1}!$"

DemoRoute_Text_AlreadyChoseStarter::
	.string "Already chose {STR_VAR_1}.\n"
	.string "Let's leave {STR_VAR_2} be.$"
