#include "global.h"
#include "text.h"
#include "dynamic_placeholder_text_util.h"
#include "string_util.h"
#include "config/text.h"

static EWRAM_DATA const u8 *sStringPointers[8] = {};

static const u8 sTextColorTable[] =
{
#if TEXT_NPC_COLORS == FALSE
    [0] = 0,
#else
    [OBJ_EVENT_GFX_BRENDAN_NORMAL]          = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_BRENDAN_MACH_BIKE]       = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_BRENDAN_SURFING]         = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE]      = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_QUINTY_PLUMP]            = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_NINJA_BOY]               = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_TWIN]                    = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_BOY_1]                   = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_GIRL_1]                  = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_BOY_2]                   = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_GIRL_2]                  = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_LITTLE_BOY]              = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_LITTLE_GIRL]             = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_BOY_3]                   = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_GIRL_3]                  = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_RICH_BOY]                = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_WOMAN_1]                 = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_FAT_MAN]                 = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_POKEFAN_F]               = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_MAN_1]                   = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_WOMAN_2]                 = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_EXPERT_M]                = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_EXPERT_F]                = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_MAN_2]                   = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_WOMAN_3]                 = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_POKEFAN_M]               = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_WOMAN_4]                 = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_COOK]                    = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_LINK_RECEPTIONIST]       = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_OLD_MAN]                 = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_OLD_WOMAN]               = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_CAMPER]                  = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_PICNICKER]               = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_MAN_3]                   = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_WOMAN_5]                 = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_YOUNGSTER]               = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_BUG_CATCHER]             = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_PSYCHIC_M]               = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_SCHOOL_KID_M]            = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_MANIAC]                  = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_HEX_MANIAC]              = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_SWIMMER_M]               = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_SWIMMER_F]               = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_BLACK_BELT]              = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_BEAUTY]                  = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_SCIENTIST_1]             = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_LASS]                    = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_GENTLEMAN]               = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_SAILOR]                  = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_FISHERMAN]               = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_RUNNING_TRIATHLETE_M]    = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_RUNNING_TRIATHLETE_F]    = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_TUBER_F]                 = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_TUBER_M]                 = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_HIKER]                   = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_CYCLING_TRIATHLETE_M]    = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_CYCLING_TRIATHLETE_F]    = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_NURSE]                   = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_BRENDAN_ACRO_BIKE]       = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_PROF_BIRCH]              = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_MAN_4]                   = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_MAN_5]                   = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_REPORTER_M]              = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_REPORTER_F]              = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_BARD]                    = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_ANABEL]                  = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_TUCKER]                  = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_GRETA]                   = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_SPENSER]                 = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_NOLAND]                  = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_LUCY]                    = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_MART_EMPLOYEE]           = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_ROOFTOP_SALE_WOMAN]      = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_TEALA]                   = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_MAY_NORMAL]              = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_MAY_MACH_BIKE]           = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_MAY_ACRO_BIKE]           = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_MAY_SURFING]             = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_MAY_FIELD_MOVE]          = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_ARTIST]                  = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_RIVAL_BRENDAN_NORMAL]    = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_RIVAL_BRENDAN_MACH_BIKE] = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_RIVAL_BRENDAN_ACRO_BIKE] = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_RIVAL_BRENDAN_SURFING]   = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_RIVAL_BRENDAN_FIELD_MOVE]= NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_RIVAL_MAY_NORMAL]        = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_RIVAL_MAY_MACH_BIKE]     = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_RIVAL_MAY_ACRO_BIKE]     = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_RIVAL_MAY_SURFING]       = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_RIVAL_MAY_FIELD_MOVE]    = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_CAMERAMAN]               = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_BRENDAN_UNDERWATER]      = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_MAY_UNDERWATER]          = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_SCIENTIST_2]             = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_DEVON_EMPLOYEE]          = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_AQUA_MEMBER_M]           = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_AQUA_MEMBER_F]           = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_MAGMA_MEMBER_M]          = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_MAGMA_MEMBER_F]          = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_SIDNEY]                  = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_PHOEBE]                  = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_GLACIA]                  = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_DRAKE]                   = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_ROXANNE]                 = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_BRAWLY]                  = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_WATTSON]                 = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_FLANNERY]                = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_NORMAN]                  = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_WINONA]                  = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_LIZA]                    = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_TATE]                    = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_WALLACE]                 = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_STEVEN]                  = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_WALLY]                   = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_LITTLE_BOY_3]            = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_BRENDAN_FISHING]         = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_MAY_FISHING]             = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_HOT_SPRINGS_OLD_WOMAN]   = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_GAMEBOY_KID]             = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_CONTEST_JUDGE]           = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_BRENDAN_WATERING]        = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_MAY_WATERING]            = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_BRENDAN_DECORATING]      = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_MAY_DECORATING]          = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_ARCHIE]                  = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_MAXIE]                   = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_TUBER_M_SWIMMING]        = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_MOM]                     = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_LINK_BRENDAN]            = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_LINK_MAY]                = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_JUAN]                    = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_SCOTT]                   = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_MYSTERY_GIFT_MAN]        = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_UNION_ROOM_NURSE]        = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_RED]                     = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_LEAF]                    = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_BRANDON]                 = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_LINK_RS_BRENDAN]         = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_LINK_RS_MAY]             = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_RED_NORMAL]              = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_RED_BIKE]                = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_RED_SURF]                = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_RED_FIELD_MOVE]          = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_RED_FISH]                = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_RED_VS_SEEKER]           = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_RED_VS_SEEKER_BIKE]      = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_UNUSED_250]              = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_GREEN_NORMAL]            = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_GREEN_BIKE]              = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_GREEN_SURF]              = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_GREEN_FIELD_MOVE]        = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_GREEN_FISH]              = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_GREEN_VS_SEEKER]         = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_GREEN_VS_SEEKER_BIKE]    = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_BOY]                     = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_CRUSH_GIRL]              = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_MAN]                     = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_ROCKER]                  = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_BALDING_MAN]             = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_OLD_MAN_1]               = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_OLD_MAN_2]               = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_OLD_MAN_LYING_DOWN]      = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_TUBER_M_WATER]           = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_TUBER_M_LAND]            = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_COOLTRAINER_M]           = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_COOLTRAINER_F]           = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_SWIMMER_M_WATER]         = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_SWIMMER_F_WATER]         = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_SWIMMER_M_LAND]          = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_SWIMMER_F_LAND]          = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_WORKER_M]                = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_WORKER_F]                = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_ROCKET_M]                = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_ROCKET_F]                = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_GBA_KID]                 = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_POKE_MANIAC_FRLG]        = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_BIKER]                   = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_BLACK_BELT_FRLG]         = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_SCIENTIST]               = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_FISHER]                  = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_CHANNELER]               = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_CHEF]                    = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_POLICEMAN]               = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_CAPTAIN]                 = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_CABLE_CLUB_RECEPTIONIST] = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_UNION_ROOM_RECEPTIONIST] = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_CLERK]                   = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_MG_DELIVERYMAN]          = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_TRAINER_TOWER_DUDE]      = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_PROF_OAK]                = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_BLUE]                    = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_BILL]                    = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_LANCE]                   = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_AGATHA]                  = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_DAISY]                   = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_LORELEI]                 = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_MR_FUJI]                 = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_BRUNO]                   = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_BROCK]                   = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_MISTY]                   = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_LT_SURGE]                = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_ERIKA]                   = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_KOGA]                    = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_SABRINA]                 = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_BLAINE]                  = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_GIOVANNI]                = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_CELIO]                   = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_TEACHY_TV_HOST]          = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_GYM_GUY]                 = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_LITTLE_BOY_FRLG]         = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_LITTLE_GIRL_FRLG]        = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_YOUNGSTER_FRLG]          = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_BUG_CATCHER_FRLG]        = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_LASS_FRLG]               = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_WOMAN_1_FRLG]            = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_FAT_MAN_FRLG]            = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_WOMAN_2_FRLG]            = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_BEAUTY_FRLG]             = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_WOMAN_3_FRLG]            = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_OLD_WOMAN_FRLG]          = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_CAMPER_FRLG]             = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_PICNICKER_FRLG]          = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_MOM_FRLG]                = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_TUBER_F_FRLG]            = NPC_TEXT_COLOR_FEMALE,
    [OBJ_EVENT_GFX_HIKER_FRLG]              = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_GENTLEMAN_FRLG]          = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_SAILOR_FRLG]             = NPC_TEXT_COLOR_MALE,
    [OBJ_EVENT_GFX_NURSE_FRLG]              = NPC_TEXT_COLOR_FEMALE,
#endif
};

void DynamicPlaceholderTextUtil_Reset(void)
{
    const u8 **ptr;
    u8 *fillval;
    const u8 **ptr2;

    ptr = sStringPointers;
    fillval = NULL;
    ptr2 = ptr + (ARRAY_COUNT(sStringPointers) - 1);
    do
    {
        *ptr2-- = fillval;
    } while ((int)ptr2 >= (int)ptr);
}

void DynamicPlaceholderTextUtil_SetPlaceholderPtr(u8 idx, const u8 *ptr)
{
    if (idx < ARRAY_COUNT(sStringPointers))
    {
        sStringPointers[idx] = ptr;
    }
}

u8 *DynamicPlaceholderTextUtil_ExpandPlaceholders(u8 *dest, const u8 *src)
{
    while (*src != EOS)
    {
        if (*src != CHAR_DYNAMIC)
        {
            *dest++ = *src++;
        }
        else
        {
            src++;
            if (sStringPointers[*src] != NULL)
            {
                dest = StringCopy(dest, sStringPointers[*src]);
            }
            src++;
        }
    }
    *dest = EOS;
    return dest;
}

const u8 *DynamicPlaceholderTextUtil_GetPlaceholderPtr(u8 idx)
{
    return sStringPointers[idx];
}

u8 GetColorFromTextColorTable(u16 graphicId)
{
    if (graphicId >= ARRAY_COUNT(sTextColorTable))
        return NPC_TEXT_COLOR_NEUTRAL;
    else
        return sTextColorTable[graphicId];
}
